#+TITLE:       GCal Facebook
#+AUTHOR:      Joost Soeterbroek
#+EMAIL:       joost.soeterbroek@gmail.com
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    GCal Facebook
#+STARTUP:     hidestars
#+STARTUP:     overview
#+FILETAGS:    facebook

* Meerhanden
  :PROPERTIES:
  :ID:        a8h00su8fhvlq4tfub0thka4e8@google.com
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-08-09 Tue 19:00-20:00>

* PolyPicknick
  :PROPERTIES:
  :ID:        CE64A2CC-DFEF-4419-9CCB-8664C0C1993D
  :LOCATION:  Flevopark, 1095 Amsterdam, Nederland
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-09-03 Sat 12:00-16:00>

Zaterdag 3 september is er weer een PolyPicknick! De formule van de picknick is Potluck: neem zelf lekkers te eten en te drinken mee om samen een uitgebreid buffet te maken. Iedereen is welkom op de picknick: mensen die poly zijn of niet, (mono-)partners, en mensen die gewoon nieuwsgierig zijn. Er is een speeltuin vlakbij de picknickplek dus neem ook je kinderen mee!

Datum
De picknick is op zaterdag 3 september van 12.00-16.00 uur in het Flevopark in Amsterdam. Leuk als je even laat weten dat je komt op info@polyamsterdam.nl.

Locatie
Flevopark in Amsterdam, http://www.flevopark.nl
Hoe kom je er? Je gaat het park in via de ingang waar tram 3 en tram 14 hun eindhalte bereiken (halte Flevopark). Daar is ook het Flevoparkbad. Er is redelijk wat parkeergelegenheid. Je kunt op googlemaps een aardig beeld krijgen. Je loopt een paar minuutjes het pad af vanaf die ingang tot je aan je rechterhand een kinderspeelplaats ziet. Je ziet dat er dan ook een pad naar links gaat. Op het flinke grasveld in die hoek zitten wij!

Kosten
Neem zelf iets te eten en drinken mee om te delen met elkaar.

Is het slecht weer? Dan proberen we een alternatief te bedenken. Wil je op de hoogte worden gehouden? Meld je dan aan op info@polyamsterdam.nl.
