#+TITLE:       GCal Werk
#+AUTHOR:      Joost Soeterbroek
#+EMAIL:       joost.soeterbroek@gmail.com
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    GCal Werk
#+STARTUP:     hidestars
#+STARTUP:     overview
#+FILETAGS:    werk

* Kantoor
  :PROPERTIES:
  :ID:        72c2timrm9eigg3k7lam6m28fg@google.com
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-08-04 Thu 09:00-16:00>

* Arbeidsvoorwaarden
  :PROPERTIES:
  :ID:        6leluolltaisl8b33451v2k3n4@google.com
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-07-22 Fri 15:00-16:00>

* Kantoor Zwolle
  :PROPERTIES:
  :ID:        7mu5rdsqsudgfonm63pbp6gcj7@google.com
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-07-19 Tue 08:30-17:30>

* Uitnodiging voor vergadering: Sprintplanning TAB+DO
  :PROPERTIES:
  :ID:        0dcb8e96-b9d4-4f81-8496-131a1ee691c8
  :LOCATION:  https 27dd0820df90f063af
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-08-04 Thu 13:00-14:30>


Adil Benkibbou nodigt u uit om deel te nemen aan deze Rijksvideo Vergadering.

Vergaderingnummer (toegangscode): 2740 912 6575
Wachtwoord voor vergadering: 8CFxiFzUc43

Gebeurt elke 3 week/weken op donderdag met ingang vandonderdag 04 augustus 2022 van 13:00 tot 14:30, (UTC+02:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen
13:00  |  (UTC+02:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen  |  1 uur 30 minuten

Deelnemen aan vergadering<https://rijksvideo.webex.com/rijksvideo/j.php?MTID=m6ac0ec3afd4e2827dd0820df90f063af>


Meer manieren om deel te nemen:

Deelnemen via de vergaderingskoppeling
https://rijksvideo.webex.com/rijksvideo/j.php?MTID=m6ac0ec3afd4e2827dd0820df90f063af

Tik om deel te nemen vanaf een mobiel apparaat (alleen deelnemers)
+31-2072-19842,,27409126575##<tel:%2B31-2072-19842,,*01*27409126575%23%23*01*> Netherlands Toll
+1-650-215-5226,,27409126575##<tel:%2B1-650-215-5226,,*01*27409126575%23%23*01*> United States Toll

Deelnemen via telefoon
+31-2072-19842 Netherlands Toll
+1-650-215-5226 United States Toll
Algemene inbelnummers<https://rijksvideo.webex.com/rijksvideo/globalcallin.php?MTID=m0cfc66a6c2d208f08c7036d08789f366>

Deelnemen via een videosysteem of -toepassing
Kies 27409126575@rijksvideo.webex.com<sip:27409126575@rijksvideo.webex.com>
U kunt ook 62.109.219.4 kiezen en uw vergaderingnummer invoeren.

Hebt u hulp nodig? Ga naar http://help.webex.com



* Uitnodiging voor vergadering: Review TAB+DO
  :PROPERTIES:
  :ID:        1228eef0-768a-4518-ace1-25e2b91d873c
  :LOCATION:  https 18093377035f2faa20
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-08-04 Thu 09:15-10:15>


Adil Benkibbou nodigt u uit om deel te nemen aan deze Rijksvideo Vergadering.

Vergaderingnummer (toegangscode): 2741 287 3011
Wachtwoord voor vergadering: Ze64amedip3

Gebeurt elke 3 week/weken op donderdag met ingang vandonderdag 04 augustus 2022 van 9:15 tot 10:15, (UTC+02:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen
9:15  |  (UTC+02:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen  |  1 uur

Deelnemen aan vergadering<https://rijksvideo.webex.com/rijksvideo/j.php?MTID=mc25135ca552d7b18093377035f2faa20>


Meer manieren om deel te nemen:

Deelnemen via de vergaderingskoppeling
https://rijksvideo.webex.com/rijksvideo/j.php?MTID=mc25135ca552d7b18093377035f2faa20

Tik om deel te nemen vanaf een mobiel apparaat (alleen deelnemers)
+31-2072-19842,,27412873011##<tel:%2B31-2072-19842,,*01*27412873011%23%23*01*> Netherlands Toll
+1-650-215-5226,,27412873011##<tel:%2B1-650-215-5226,,*01*27412873011%23%23*01*> United States Toll

Deelnemen via telefoon
+31-2072-19842 Netherlands Toll
+1-650-215-5226 United States Toll
Algemene inbelnummers<https://rijksvideo.webex.com/rijksvideo/globalcallin.php?MTID=m3503701b7498f205ed18ef7b6392afb8>

Deelnemen via een videosysteem of -toepassing
Kies 27412873011@rijksvideo.webex.com<sip:27412873011@rijksvideo.webex.com>
U kunt ook 62.109.219.4 kiezen en uw vergaderingnummer invoeren.

Hebt u hulp nodig? Ga naar http://help.webex.com



* Uitnodiging voor vergadering: Retrospective TAB+DO
  :PROPERTIES:
  :ID:        f0c87fa1-58b7-418f-b445-7b9d25bb67ac
  :LOCATION:  https d22f53fec23dcd90bc
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-08-04 Thu 10:15-11:00>


Adil Benkibbou nodigt u uit om deel te nemen aan deze Rijksvideo Vergadering.

Vergaderingnummer (toegangscode): 2742 707 6315
Wachtwoord voor vergadering: gsCJjqWn768

Gebeurt elke 3 week/weken op donderdag met ingang vandonderdag 04 augustus 2022 van 10:15 tot 11:00, (UTC+02:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen
10:15  |  (UTC+02:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen  |  45 minuten

Deelnemen aan vergadering<https://rijksvideo.webex.com/rijksvideo/j.php?MTID=m482804e4556bb5d22f53fec23dcd90bc>


Meer manieren om deel te nemen:

Deelnemen via de vergaderingskoppeling
https://rijksvideo.webex.com/rijksvideo/j.php?MTID=m482804e4556bb5d22f53fec23dcd90bc

Tik om deel te nemen vanaf een mobiel apparaat (alleen deelnemers)
+31-2072-19842,,27427076315##<tel:%2B31-2072-19842,,*01*27427076315%23%23*01*> Netherlands Toll
+1-650-215-5226,,27427076315##<tel:%2B1-650-215-5226,,*01*27427076315%23%23*01*> United States Toll

Deelnemen via telefoon
+31-2072-19842 Netherlands Toll
+1-650-215-5226 United States Toll
Algemene inbelnummers<https://rijksvideo.webex.com/rijksvideo/globalcallin.php?MTID=m56d6e3e5303324ef1c87c45729421d95>

Deelnemen via een videosysteem of -toepassing
Kies 27427076315@rijksvideo.webex.com<sip:27427076315@rijksvideo.webex.com>
U kunt ook 62.109.219.4 kiezen en uw vergaderingnummer invoeren.

Hebt u hulp nodig? Ga naar http://help.webex.com



* Uitnodiging voor vergadering: Refinement TAB+DO
  :PROPERTIES:
  :ID:        d1f65cbd-0814-4f4b-812e-fcecb85c0520
  :LOCATION:  https aa250d51046436d754
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-07-28 Thu 13:00-14:00>

Backlog Refinement ter voorbereiding van Sprintplanning
-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-

Adil Benkibbou nodigt u uit om deel te nemen aan deze Rijksvideo Vergadering.

Vergaderingnummer (toegangscode): 2744 909 6125
Wachtwoord voor vergadering: D6pw3AP7p6h

Gebeurt elke 3 week/weken op donderdag met ingang vandonderdag 28 juli 2022 van 13:00 tot 14:00, (UTC+02:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen
13:00  |  (UTC+02:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen  |  1 uur

Deelnemen aan vergadering<https://rijksvideo.webex.com/rijksvideo/j.php?MTID=m9f665b90944240aa250d51046436d754>


Meer manieren om deel te nemen:

Deelnemen via de vergaderingskoppeling
https://rijksvideo.webex.com/rijksvideo/j.php?MTID=m9f665b90944240aa250d51046436d754

Tik om deel te nemen vanaf een mobiel apparaat (alleen deelnemers)
+31-2072-19842,,27449096125##<tel:%2B31-2072-19842,,*01*27449096125%23%23*01*> Netherlands Toll
+1-650-215-5226,,27449096125##<tel:%2B1-650-215-5226,,*01*27449096125%23%23*01*> United States Toll

Deelnemen via telefoon
+31-2072-19842 Netherlands Toll
+1-650-215-5226 United States Toll
Algemene inbelnummers<https://rijksvideo.webex.com/rijksvideo/globalcallin.php?MTID=m3a06e8f29bd6fb1c67314ad28f5f302b>

Deelnemen via een videosysteem of -toepassing
Kies 27449096125@rijksvideo.webex.com<sip:27449096125@rijksvideo.webex.com>
U kunt ook 62.109.219.4 kiezen en uw vergaderingnummer invoeren.

Hebt u hulp nodig? Ga naar http://help.webex.com



* Uitnodiging voor vergadering: Refinement TAB+DO
  :PROPERTIES:
  :ID:        25dca646-0115-40fa-839d-e7526a9bfe75
  :LOCATION:  https f394c4d6d119b1e305
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-07-21 Thu 13:00-14:00>

Backlog Refinement ter voorbereiding van Sprintplanning
-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-

Adil Benkibbou nodigt u uit om deel te nemen aan deze Rijksvideo Vergadering.

Vergaderingnummer (toegangscode): 2740 813 9374
Wachtwoord voor vergadering: MDrTsmsY535

Gebeurt elke 3 week/weken op donderdag met ingang vandonderdag 21 juli 2022 van 13:00 tot 14:00, (UTC+02:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen
13:00  |  (UTC+02:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen  |  1 uur

Deelnemen aan vergadering<https://rijksvideo.webex.com/rijksvideo/j.php?MTID=m2717c44f1bd719f394c4d6d119b1e305>


Meer manieren om deel te nemen:

Deelnemen via de vergaderingskoppeling
https://rijksvideo.webex.com/rijksvideo/j.php?MTID=m2717c44f1bd719f394c4d6d119b1e305

Tik om deel te nemen vanaf een mobiel apparaat (alleen deelnemers)
+31-2072-19842,,27408139374##<tel:%2B31-2072-19842,,*01*27408139374%23%23*01*> Netherlands Toll
+1-650-215-5226,,27408139374##<tel:%2B1-650-215-5226,,*01*27408139374%23%23*01*> United States Toll

Deelnemen via telefoon
+31-2072-19842 Netherlands Toll
+1-650-215-5226 United States Toll
Algemene inbelnummers<https://rijksvideo.webex.com/rijksvideo/globalcallin.php?MTID=m0c93a4b23dfd71b6be743a1a97ecd786>

Deelnemen via een videosysteem of -toepassing
Kies 27408139374@rijksvideo.webex.com<sip:27408139374@rijksvideo.webex.com>
U kunt ook 62.109.219.4 kiezen en uw vergaderingnummer invoeren.

Hebt u hulp nodig? Ga naar http://help.webex.com



* Uitnodiging voor vergadering: Refinement LINUX Expertise Team incl BOO
  :PROPERTIES:
  :ID:        e214de13-b54b-4cfd-be31-53305213bb27
  :LOCATION:  https ead3d7717062cb4d12
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-07-28 Thu 13:00-14:00>


Welink. L.C. (Luc) nodigt u uit om deel te nemen aan deze Rijksvideo Vergadering.

Vergaderingnummer (toegangscode): 2740 883 2670
Wachtwoord voor vergadering: vwJmp3ZVF83

Gebeurt elke 3 week/weken op donderdag met ingang vandonderdag 20 januari 2022 van 13:00 tot 14:00, (UTC+01:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen
13:00  |  (UTC+01:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen  |  1 uur

Deelnemen aan vergadering<https://rijksvideo.webex.com/rijksvideo/j.php?MTID=m467ba1b727832cead3d7717062cb4d12>


Meer manieren om deel te nemen:

Deelnemen via de vergaderingskoppeling
https://rijksvideo.webex.com/rijksvideo/j.php?MTID=m467ba1b727832cead3d7717062cb4d12

Tik om deel te nemen vanaf een mobiel apparaat (alleen deelnemers)
+31-2072-19842,,27408832670##<tel:%2B31-2072-19842,,*01*27408832670%23%23*01*> Netherlands Toll
+1-650-215-5226,,27408832670##<tel:%2B1-650-215-5226,,*01*27408832670%23%23*01*> United States Toll

Deelnemen via telefoon
+31-2072-19842 Netherlands Toll
+1-650-215-5226 United States Toll
Algemene inbelnummers<https://rijksvideo.webex.com/rijksvideo/globalcallin.php?MTID=m27eccaa79f76bdcc3d7f5f9e6d011d35>

Deelnemen via een videosysteem of -toepassing
Kies 27408832670@rijksvideo.webex.com<sip:27408832670@rijksvideo.webex.com>
U kunt ook 62.109.219.4 kiezen en uw vergaderingnummer invoeren.

Hebt u hulp nodig? Ga naar http://help.webex.com



* Tijdschrijven
  :PROPERTIES:
  :ID:        040000008200E00074C5B7101A82E0080000000040A58E1A9642D301000000000000000
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-07-15 Fri 08:00-08:30>

Beste mensen,

Deze afspraak zet ik in jullie agenda’s om centraal iedereen te herinneren aan het insturen van de urenstaat voor deze week.
Dat mag op een voor jou geschikt moment, als het maar op deze vrijdag gebeurt.
Als het nog niet kan omdat je bijvoorbeeld in het weekend gaat werken, verstuur dan de urenstaat uiterlijk maandag a.s. vóór 9 uur.

Op maandagochtend kunnen de goedkeurders (o.a. Product Owners, Delivery Managers en Teamleider) dan nog hun akkoord geven. Ook kan dan de facturatie-run op tijd en compleet worden uitgevoerd.

Los van deze afspraak, moeten we ook de urenstaten op de laatste dag van de maand versturen, en dan wel gelijk voor die hele week.

Hiermee bereiken we dat facturen volledig zijn, projectrapportages financieel juist zijn, en onze financiële voorspelbaarheid groter is in projecten en het maandelijks beheerbudget.
Bedankt voor het tijdig schrijven van je uren!

Met vriendelijke groet,

Erik van der Hout
Directie Infrastructuur
Divisie Hoog Beveiligd
Teamleider Projecten
........................................................................
DICTU
Bezuidenhoutseweg 73| 2594 AC | Den Haag
Postbus 20401 | 2500 EK | Den Haag
........................................................................
T 088 0413659
M 0615100100
e.j.g.vanderhout@dictu.nl <mailto:e.j.g.vanderhout@dictu.nl>





* Linux voorzieingen autom. patching
  :PROPERTIES:
  :ID:        040000008200E00074C5B7101A82E00800000000A01A67455C85D801000000000000000
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-07-26 Tue 19:00-23:00>

* Gele tafel (sessies 2022 op de dinsdag)
  :PROPERTIES:
  :ID:        040000008200E00074C5B7101A82E008000000000088965463EBD701000000000000000
  :LOCATION:  Microsoft Teams-vergadering
  :STATUS:    CONFIRMED
  :ATTENDING: ATTENDING
  :ATTENDEES: 
  :END:
<2022-07-26 Tue 11:30-12:00>

